// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.example.grpc;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
